[package]
name = "rust_tekxchange_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
argon2 = { version = "0.4.1", features = ["parallel"] }
chrono = {version = "0.4.23", features = ["serde"]}
diesel = { version = "2.0.2", features = ["postgres", "serde_json", "chrono", "uuid", "time"] }
dotenvy = "0.15.6"
rocket = {version = "0.5.0-rc.2", features = ["json"]}
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.91"
thiserror = "1.0.38"
