services:
  
  db:
    image: postgres:12.13-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  statsd:
    image: graphiteapp/graphite-statsd
    ports:
      - "8125:8125/udp"
      - "8080"

  grafana:
    image: grafana/grafana:9.5.1
    ports:
      - "3000:3000"

  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./devel.Dockerfile
  #     target: localdev
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis
  #     - statsd
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./:/usr/src/app:z