services:
  
  db:
    image: postgres:12.13-alpine
    env_file:
      - ./prod.env
    ports:
      - 5432:5432

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./prod.env