services:
  
  db:
    image: postgres:12.13-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: ./devel.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app:z