name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        submodules: recursive
        ssh-key: ${{ secrets.REPO_SSH_KEY }}

    - name: Docker login and setup
      uses: docker/login-action@v1.9.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ${{ github.actor }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/tekxchange/backend_webservice:latest --target RUNNER .

    - name: Publish Docker image
      run: docker image push ghcr.io/tekxchange/backend_webservice:latest
