//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "picture")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub file_location: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_picture::Entity")]
    ProductPicture,
}

impl Related<super::product_picture::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductPicture.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
